 const ar = { home: "الرئيسية",
            specialties: "التخصصات",
            doctors: "الأطباء",
            clinics: "العيادات",
            appointments: "المواعيد",
            about: "من نحن",
            contact: "اتصل بنا",
            login: "تسجيل الدخول",
            createAccount: "إنشاء حساب",
            footer: {
            desc: "منصة ذكية لحجز الرعاية الصحية تربط المرضى بأفضل الأطباء والعيادات.",
            searchTitle: "ابحث عبر",
            supportTitle: "الدعم",
            teamTitle: "الفريق",
            contactTitle: "اتصل بنا",
            hours: "ساعات الدعم",
            rights: "جميع الحقوق محفوظة © Medaura",
            home: "الرئيسية",
            specialties: "التخصصات",
            doctors: "الأطباء",
            appointments: "مواعيدي",
            offers: "العروض",
            about: "من نحن",
            helpCenter: "مركز المساعدة",
            contactUs: "تواصل معنا",
            privacy: "سياسة الخصوصية",
            terms: "شروط الخدمة",
            join: "انضم للفريق",
            apply: "التقديم للفريق",
            teamSupport: "دعم الفريق",
            }
            ,
            specialtiesPage: {
            badge: "جميع التخصصات الطبية ",
            title: "اختر التخصص المناسب",
            subtitle: "احجز موعدك مع أفضل الأطباء في غضون دقائق",
            search: "ابحث عن تخصص...",
            doctor: "طبيب",
            button: "عرض الأطباء",
            sectionTitle: "التخصصات الطبية",
            viewAll: "عرض جميع الأطباء",
            cardiology: "قلب وأوعية دموية",
            neurology: "مخ وأعصاب",
            orthopedics: "عظام",
            pulmonology: "صدر وجهاز تنفسي",
            nephrology: "كلى",
            oncology: "أورام",
            ent: "أنف وأذن وحنجرة",
            ophthalmology: "طب العيون",
            obgyn: "نساء وتوليد",
            dermatology: "جلدية",
            dentistry: "أسنان",
            pediatrics: "أطفال وحديثي الولادة",
            specialtiesCount: "تخصص طبي",
            availableDoctors: "طبيب متاح",
            noResults: "لا توجد تخصصات مطابقة"
},
    patients: {
            title: "المرضى",
            count: "مريض",
            search: "بحث عن مريض...",
            name: "الاسم",
            gender: "الجنس",
            department: "القسم",
            lastVisit: "آخر زيارة",
            noPatients: "لا يوجد مرضى"
},
    hero: {
            badge: "منصة رعاية صحية موثوقة",
            typing:"سجل الآن في Medaura واستفد من الذكاء الاصطناعي في المجال الطبي. صف أعراضك لمساعدنا الذكي ودعنا نرشدك إلى الطبيب المناسب.",
            title1: "صحتك تبدأ من هنا",
            title2: "احجز أفضل الأطباء في دقائق",
            description:"ابحث عن التخصص المناسب، وقارن بين أفضل الأطباء، واحجز موعدك بسهولة وسرعة.",
            bookNow: "احجز الآن",
            explore: "استكشف التخصصات",
            happyPatients: "مرضى سعداء",
            licensedDoctors: "أطباء مرخصون",
            alwaysAvailable: "متاحون دائمًا"
},
    specialtiesPanel: {
            title: "التخصصات الطبية",
            subtitle: "اختر التخصص المناسب واعثر على أفضل الأطباء لحالتك.",
            viewAll: "عرض الكل",
            doctors: "طبيب",
            neurology: "مخ وأعصاب",
            orthopedics: "عظام",
            oncology: "أورام",
            ent: "أنف وأذن وحنجرة",
            ophthalmology: "طب العيون",
            cardiology: "قلب وأوعية دموية",
            pulmonology: "صدر وجهاز تنفسي",
            nephrology: "كلى",
            dentistry: "أسنان",
            pediatrics: "أطفال",
            dermatology: "جلدية",
            gynecology: "نساء وتوليد"
},
    structure: {
            title: "كيف يعمل الموقع",
            subtitle: "ثلاث خطوات بسيطة للعثور على الطبيب المناسب وحجز موعدك.",
            step: "الخطوة",
            step1Title: "ابحث حسب التخصص",
            step1Desc:"تصفح التخصصات وابحث عن الطبيب المناسب وفقًا لحالتك الطبية.",
            step2Title: "اختر طبيبك",
            step2Desc:"قارن بين التقييمات والأسعار وموقع العيادة قبل اختيار الطبيب.",
            step3Title: "احجز فورًا",
            step3Desc:"احجز موعدك خلال ثوانٍ واحصل على تأكيد الحجز مباشرة."
},
    aboutPage: {
            badge: "ميداورا",
            title: "من نحن",
            description1:"في ميداورا نؤمن بأن الوصول إلى الرعاية الصحية يجب أن يكون سهلاً وسريعًا. نربط المرضى بأفضل الأطباء والعيادات، ونساعدهم على اختيار التخصص المناسب وحجز المواعيد بكل سهولة وثقة.",
            description2:"هدفنا هو جعل تجربة البحث والحجز أكثر وضوحًا وسلاسة، بدايةً من مقارنة تقييمات الأطباء وأسعار الكشف وحتى تأكيد الموعد، مع الحفاظ على جودة الخدمة وراحة المريض في كل خطوة.",
            feature1: "رعاية موثوقة",
            feature2: "حجز أسرع",
            feature3: "أطباء معتمدون"
},
    appointmentsPage: {
            badge: "الحجوزات",
            title: "المواعيد القادمة وسجل الزيارات",
            filter: "تصفية بالتاريخ",
            apply: "تطبيق",
            total: "إجمالي الحجوزات",
            today: "حجوزات اليوم",
            current: "المعروضة الآن",
            empty: "لا توجد حجوزات مطابقة للتاريخ المحدد."
},
    testimonials: {
            title: "آراء المرضى",
            subtitle: "تجارب حقيقية من المرضى الذين حجزوا عبر Medaura.",
            text1: "كانت عملية الحجز سهلة جدًا، ووصلت للطبيب المناسب بسرعة. وكانت تجربة العيادة ممتازة.",
            text2: "قدرت أقارن بين الأطباء من حيث التقييم وسعر الكشف في دقائق، وتم تأكيد الحجز فورًا.",
            text3: "منصة ممتازة لحجز مواعيد الأسرة، معلومات واضحة، ودعم سريع، وعيادات موثوقة."
},
    clinicBest: {
            title: "أفضل العيادات",
            subtitle: "عيادات موثوقة بتقييمات عالية وتجهيزات حديثة.",
            viewAll: "عرض جميع العيادات",
            viewProfile: "عرض الملف",
            location: "الموقع"
},
    doctorsDetails: {
            title: "الأطباء الأكثر حجزًا",
            subtitle: "احجز موعدك مع أكثر الأطباء طلبًا وأعلى تقييمًا.",
            viewAll: "عرض جميع الأطباء",
            viewProfile: "عرض الملف الشخصي",
            sessionFee: "سعر الكشف",
            experience: "الخبرة",
            years: "سنة",
            consultantOrthopedics: "استشاري جراحة العظام",
            consultantDentistry: "استشاري طب الأسنان",
            consultantCardiology: "استشاري أمراض القلب",
            badge: "✨ أفضل الأطباء المعتمدين في مصر",
            searchPlaceholder: "ابحث باسم الطبيب أو التخصص...",
            allSpecialties: "كل التخصصات",
            neurology: "الأعصاب",
            orthopedics: "العظام",
            oncology: "الأورام",
            ent: "الأنف والأذن والحنجرة",
            ophthalmology: "العيون",
            cardiology: "القلب",
            pulmonology: "الرئة",
            nephrology: "الكلى",
            dentistry: "الأسنان",
            pediatrics: "الأطفال",
            dermatology: "الجلدية",
            obgyn: "النساء والتوليد",
            allPrices: "كل الأسعار",
            consultationPrice: "سعر الكشف",
            under200: "أقل من 200 جنيه",
            "200to500": "200 - 500 جنيه",
            "500to1000": "500 - 1000 جنيه",
            over1000: "أكثر من 1000 جنيه",
            gender: "النوع",
            all: "الكل",
            male: "ذكر",
            female: "أنثى",
            sortBy: "ترتيب حسب",
            topRated: "الأعلى تقييمًا",
            priceLowHigh: "السعر: من الأقل للأعلى",
            priceHighLow: "السعر: من الأعلى للأقل",
            alphabetical: "أبجديًا (أ - ي)",
            showing: "عرض",
            page: "الصفحة",
            of: "من",
            doctors: "طبيب"
},
    login: {
            logo: "ميداورا",
            login: "تسجيل الدخول",
            signUp: "إنشاء حساب",
            email: "البريد الإلكتروني",
            emailPlaceholder: "example@email.com",
            password: "كلمة المرور",
            passwordPlaceholder: "أدخل كلمة المرور",
            rememberMe: "تذكرني",
            forgotPassword: "نسيت كلمة المرور؟",
            noAccount: "ليس لديك حساب؟",
            invalidEmail: "من فضلك أدخل بريدًا إلكترونيًا صحيحًا",
            emailRequired: "البريد الإلكتروني مطلوب",
            passwordRequired: "كلمة المرور مطلوبة",
            passwordMin: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
            loading: "جاري تسجيل الدخول...",
            success: "تم تسجيل الدخول بنجاح.",
            loginFailed: "البريد الإلكتروني أو كلمة المرور غير صحيحة."
},
    register: {
            nameRequired: "الاسم مطلوب",
            invalidEmail: "البريد الإلكتروني غير صالح",
            emailRequired: "البريد الإلكتروني مطلوب",
            passwordStrong: "كلمة المرور يجب أن تحتوي على حرف ورقم على الأقل (8 خانات)",
            passwordRequired: "كلمة المرور مطلوبة",
            passwordMatch: "كلمة المرور غير متطابقة",
            confirmPasswordRequired: "تأكيد كلمة المرور مطلوب",
            agreeRequired: "يجب الموافقة على الشروط",
            specializationRequired: "التخصص مطلوب للأطباء",
            registerFailed: "حدث خطأ أثناء التسجيل، حاول مرة أخرى",
            patient: "مريض",
            doctor: "طبيب",
            fullName: "الاسم الكامل",
            specialization: "التخصص",
            chooseSpecialization: "اختر التخصص",
            cardiology: "طب القلب",
            dermatology: "طب الجلدية",
            neurology: "طب الأعصاب",
            pediatrics: "طب الأطفال",
            psychiatry: "الطب النفسي",
            radiology: "الأشعة",
            surgery: "الجراحة",
            email: "البريد الإلكتروني",
            emailPlaceholder: "أدخل بريدك الإلكتروني",
            password: "كلمة المرور",
            passwordPlaceholder: "أدخل كلمة المرور",
            confirmPassword: "تأكيد كلمة المرور",
            confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
            agree: "أوافق على الشروط والأحكام",
            login: "تسجيل الدخول",
            signUp: "إنشاء حساب",
            loading: "جاري التسجيل..."
},
    forgetPassword: {
            login: "تسجيل الدخول",
            signUp: "إنشاء حساب",
            title: "نسيت كلمة المرور",
            subtitle: "لا تقلق، سنرسل لك تعليمات لإعادة تعيين كلمة المرور.",
            email: "البريد الإلكتروني",
            emailPlaceholder: "example@email.com",
            send: "إرسال",
            backToLogin: "العودة لتسجيل الدخول",
            invalidEmail: "يرجى إدخال بريد إلكتروني صحيح",
            emailRequired: "البريد الإلكتروني مطلوب",
            loading: "جارٍ الإرسال...",
            success: "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.",
            failed: "حدث خطأ، حاول مرة أخرى."
},
    resetPassword: {
            title: "إعادة تعيين كلمة المرور",
            subtitle: "أدخل كلمة المرور الجديدة",
            newPassword: "كلمة المرور الجديدة",
            newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
            confirmPassword: "تأكيد كلمة المرور",
            confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
            reset: "تغيير كلمة المرور",
            loading: "جارٍ الحفظ...",
            success: "تم تغيير كلمة المرور بنجاح",
            failed: "فشل تغيير كلمة المرور"
},
    verifyOtp: {
            title: "تأكيد رمز التحقق",
            subtitle: "أدخل رمز التحقق المرسل إلى بريدك الإلكتروني.",
            email: "البريد الإلكتروني",
            verify: "تأكيد",
            loading: "جارٍ التحقق...",
            success: "تم التحقق من الرمز بنجاح.",
            failed: "رمز التحقق غير صحيح.",
            invalidCode: "من فضلك أدخل رمز مكون من 6 أرقام.",
            didntReceive: "لم تستلم الرمز؟",
            resend: "إعادة إرسال الرمز",
            resent: "تم إرسال الرمز مرة أخرى."
},

    contactDetails: {
            title: "الصفحة غير موجودة",
            description: "عذرًا، الصفحة التي تبحث عنها غير موجودة أو تم نقلها إلى مكان آخر.",
            backHome: "العودة للرئيسية"
},
    clinicsPage: {
            title: "العيادات",
            subtitle: "أفضل العيادات حسب آراء وتجارب المستخدمين",
            search: "ابحث عن عيادة بالاسم أو المدينة...",
            doctors: "الأطباء",
            details: "عرض التفاصيل",
            noResults: "لا توجد عيادات مطابقة"
},
    navbar: {
            search: "ابحث...",
            lightMode: "الوضع الفاتح",
            darkMode: "الوضع الداكن",
            notifications: "الإشعارات",
            notification: "إشعار",
            markAllRead: "تحديد الكل كمقروء",
            noNotifications: "لا توجد إشعارات",
            clearAll: "مسح الكل",
            viewAll: "عرض الكل",
            logout: "تسجيل الخروج",
            openSidebar: "فتح القائمة",
            now: "الآن",
            defaultDoctor: "د. محمد إسماعيل",
            defaultSpecialist: "طبيب قلب"
},
    chartBar: {
            title: "إحصائيات المرضى",
            showAll: "عرض الكل",
            newPatients: "مرضى جدد",
            existingPatients: "مرضى قدامى",
            totalPatients: "إجمالي المرضى",
            noData: "لا توجد بيانات",
            noDataSubtitle: "لا تتوفر بيانات لهذه الفترة"
    },
    dashboardHeader: {
            title: "نظرة عامة",
            subtitle: "متابعة الأداء والزيارات اليومية",
            chooseDate: "اختر التاريخ",
            cancel: "إلغاء",
            apply: "تطبيق"
    },
    ProfileDetail: {
            welcome: "مرحبًا بك في ملف المريض",
            summaryDesc: "هنا تجد ملخص حسابك، سجل الزيارات، الوصفات الطبية، وكل ما تحتاجه لتتبع حالتك الصحية بسهولة.",
            visits: "الزيارات",
            prescriptions: "الوصفات",
            generalError: "حدث خطأ",
            defaultUser: "مستخدم",
            lastUpdate: "أحدث تحديث",
            patientName: "اسم المريض",
            email: "البريد الإلكتروني",
            phone: "رقم الهاتف",
            dob: "تاريخ الميلاد",
            gender: "النوع",
            quickMenu: "القائمة السريعة",
            navProfile: "الملف الشخصي",
            navHistory: "سجل الزيارات",
            navPrescriptions: "الوصفات الطبية",
            navFollowup: "المتابعة",
            updateProfile: "تحديث الملف الشخصي",
            profileSubtitle: "نمذج بياناتك الشخصية",
            profilePhoto: "صورة الملف الشخصي",
            noPhoto: "لا توجد صورة",
            chooseNewPhoto: "اختر صورة جديدة",
            patient: "المريض",
            photoRequirements: "JPG, PNG بحد أقصى 5MB",
            changePhoto: "تغيير الصورة",
            savePhoto: "حفظ الصورة",
            savingPhoto: "جارٍ الرفع...",
            photoSuccess: "تم تحديث الصورة بنجاح.",
            fullNameLabel: "الاسم الكامل",
            phonePlaceholder: "010XXXXXXXX",
            genderUnspecified: "غير محدد",
            genderMale: "ذكر",
            genderFemale: "أنثى",
            changesSuccess: "تم حفظ التغييرات بنجاح.",
            saveChanges: "حفظ التغييرات",
            savingChanges: "جارٍ الحفظ...",
            reset: "إعادة تعيين",
            changePasswordTitle: "تغيير كلمة المرور",
            changePasswordSubtitle: "تحديث كلمة المرور الخاصة بك",
            currentPasswordLabel: "كلمة المرور الحالية",
            newPasswordLabel: "كلمة المرور الجديدة",
            confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
            updatePasswordBtn: "تحديث كلمة المرور",
            updatingPassword: "جارٍ التحديث...",
            historyTitle: "سجل زياراتك",
            historySubtitle: "آخر زيارات",
            historyCount: "عرض {count} زيارة",
            loadingHistory: "جارٍ تحميل السجل...",
            noHistory: "لا توجد زيارات حتى الآن.",
            doctor: "الطبيب",
            time: "الوقت",
            pendingAccess: "الطبيب يطلب إذنك لكتابة روشتة طبية لهذا الحجز",
            accept: "قبول",
            reject: "رفض",
            acceptedAccess: "تم منح الطبيب صلاحية كتابة الروشتة",
            revokeAccess: "إلغاء الصلاحية",
            rejectedAccess: "تم رفض/إلغاء صلاحية الروشتة",
            allowAccess: "السماح بالوصول",
            prescriptionsTitle: "الوصفات الطبية",
            prescriptionsSubtitle: "الوصفات الأخيرة",
            prescriptionsCount: "عرض {count} وصفة",
            loadingPrescriptions: "جارٍ تحميل الوصفات...",
            noPrescriptions: "لا توجد وصفات طبية بعد.",
            noDate: "بدون تاريخ",
            prescriptionNumber: "وصفة #{id}",
            diagnosis: "التشخيص",
            medication: "الدواء",
            tests: "الفحوصات",
            notes: "ملاحظات",
            prescriptionDetails: "تفاصيل الوصفة",
            dose: "الجرعة",
            duration: "المدة",
            forDuration: "لمدة {duration}",
            followupTitle: "متابعة الحالة",
            followupSubtitle: "خطة المتابعة",
            followupDesc: "تحديث سريع لحالتك الصحية",
            recommendationsTitle: "التوصيات",
            recommendationsText: "تابع مع الطبيب بانتظام، احرص على تسجيل الأعراض، واحضر نتائج التحاليل في كل زيارة.",
            tipsTitle: "نصائح مهمه",
            tipsText: "يمكنك تحديث رقم الهاتف والملاحظات الخاصة بك في أي وقت ثم الضغط على حفظ للتأكد من وصول الرسائل بسهولة.",
            notAvailable: "غير متوفر",
            checkingAccount: "جارٍ التحقق من حسابك...",
            needLoginTitle: "أنت بحاجة لتسجيل الدخول",
            needLoginDesc: "يرجى تسجيل الدخول أولاً لعرض صفحتك الشخصية وسجل زياراتك.",
            status: "الحالة",
            successAlert: "تم بنجاح!",
            successMsg: "تم تغيير كلمة المرور بنجاح",
            alertError: "خطأ",
            alertFillFields: "الرجاء تعبئة جميع حقول كلمة المرور",
            alertMinLength: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
            alertMatchError: "كلمة المرور الجديدة وتأكيدها غير متطابقتين",
            changePasswordFail: "فشل تغيير كلمة المرور",
            symptoms: "الأعراض",
            logout: "تسجيل الخروج",
},
    bookingStatus: {
            "pending": "قيد الانتظار",
            "confirmed": "مؤكد",
            "completed": "مكتمل",
            "cancelled": "ملغي"
},
    visitsGauge: {
            showAll: "عرض الكل",
            title: "زيارات المرضى",
            allPatients: "كل المرضى",
            male: "ذكر",
            female: "أنثى",
            sinceLastWeek: "منذ الأسبوع الماضي"
},
    sidebar: {
            home: "الرئيسية",
            healthcare: "الرعاية الصحية",
            management: "الإدارة",
            dashboard: "لوحة التحكم",
            patients: "المرضى",
            appointments: "المواعيد",
            prescriptions: "الوصفات الطبية",
            financial: "المالية",
            notifications: "الإشعارات",
            settings: "الإعدادات",
            doctorDashboard: "لوحة الطبيب",
            closeSidebar: "إغلاق القائمة"
},
    adminDash: {
            totalDoctors: "إجمالي الأطباء",
            totalPatients: "إجمالي المرضى",
            totalClinics: "إجمالي العيادات",
            totalStaff: "إجمالي الموظفين",
    },
    notificationsPage: {
      title: 'الإشعارات',
      subtitle: 'ابق على اطلاع بآخر التنبيهات.',
      backHome: 'العودة للرئيسية',
      markAllRead: 'تحديد الكل كمقروء',
      loading: 'جاري تحميل الإشعارات...',
      noNotifications: 'لا توجد إشعارات بعد',
      noNotificationsDesc: 'أنت على اطلاع دائم! سنقوم بإعلامك عند حدوث شيء مهم.',
      newNotification: 'إشعار جديد',
      markAsRead: 'تحديد كمقروء',
      recently: 'مؤخراً',
      error: 'خطأ: '
    },
    contactPage: {
      getInTouch: 'تواصل معنا',
      title: 'اتصل بنا',
      subtitle: 'هل لديك أسئلة أو تحتاج إلى مساعدة؟ نحن هنا للمساعدة! أرسل لنا رسالة وسيقوم فريقنا بالرد عليك قريبًا.',
      callUs: 'اتصل بنا',
      callUsDesc: 'السبت-الخميس من 9 صباحاً إلى 6 مساءً.',
      emailUs: 'راسلنا عبر البريد',
      emailUsDesc: 'عادة ما نرد خلال 24 ساعة.',
      visitUs: 'قم بزيارتنا',
      visitUsDesc1: '١٢٣ شارع الصحة، الحي الطبي',
      visitUsDesc2: 'القاهرة، مصر',
      sendMessage: 'أرسل رسالة',
      messageSent: 'تم إرسال الرسالة بنجاح!',
      messageSentDesc: 'شكراً لتواصلك معنا. لقد تلقينا رسالتك وسنتصل بك قريباً.',
      sendAnother: 'أرسل رسالة أخرى',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      subject: 'الموضوع',
      message: 'الرسالة',
      namePlaceholder: 'أحمد محمد',
      emailPlaceholder: 'ahmed@example.com',
      subjectPlaceholder: 'كيف يمكننا مساعدتك؟',
      messagePlaceholder: 'اكتب رسالتك هنا...',
      sendBtn: 'إرسال الرسالة'
    },
    dashboard: {
            sidebar: {
                    home: "الرئيسية",
                    healthcare: "الرعاية الصحية",
                    management: "الإدارة",
                    dashboard: "لوحة التحكم",
                    patients: "المرضى",
                    doctors: "الأطباء",
                    appointments: "المواعيد",
                    clinicDoctors: "أطباء العيادات",
                    clinics: "العيادات",
                    staff: "الموظفين",
                    auditLogs: "سجل النظام",
                    notifications: "الإشعارات",
                    settings: "الإعدادات"
            }
    }
};
export default ar;