const en = {  home: "Home",
            specialties: "Specialties",
            doctors: "Doctors",
            clinics: "Clinics",
            appointments: "Appointments",
            about: "About",
            contact: "Contact",
            login: "Login",
            createAccount: "Create account",
            footer: {
            desc: "Smart healthcare booking platform connecting patients with top doctors and clinics.",
            searchTitle: "Search by",
            supportTitle: "Support",
            teamTitle: "Team",
            contactTitle: "Contact",
            hours: "Support hours",
            rights: "© Medaura. All rights reserved.",
            home: "Home",
            specialties: "Specialties",
            doctors: "Doctors",
            appointments: "My Appointments",
            offers: "Offers",
            about: "About Us",
            helpCenter: "Help Center",
            contactUs: "Contact Us",
            privacy: "Privacy Policy",
            terms: "Terms of Service",
            join: "Join our Team",
            apply: "Apply to Join",
            teamSupport: "Team Support"
            }
            ,
    specialtiesPage: {
            badge: "Medical Specialties",
            title: "Choose the right specialty",
            subtitle: "Book your appointment with the best doctors in minutes",
            search: "Search for specialty...",
            doctor: "Doctor",
            button: "View Doctors",
            sectionTitle: "Medical Specialties",
            viewAll: "View All Doctors",
            cardiology: "Cardiology",
            neurology: "Neurology",
            orthopedics: "Orthopedics",
            pulmonology: "Pulmonology",
            nephrology: "Nephrology",
            oncology: "Oncology",
            ent: "ENT",
            ophthalmology: "Ophthalmology",
            obgyn: "OB-GYN",
            dermatology: "Dermatology",
            dentistry: "Dentistry",
            pediatrics: "Pediatrics",
            specialtiesCount: "Medical Specialties",
            availableDoctors: "Available Doctors",
            noResults: "No specialties found"
},
    hero: {
            badge: "Trusted healthcare platform",
            typing:"Register now in Medaura and benefit from AI in the medical field. Describe your symptoms to our smart assistant, and let us guide you to the right doctor.",
            title1: "Your health starts here",
            title2: "Book the best doctors in minutes",
            description:"Find the right specialty, compare top-rated doctors, and schedule your next visit in a fast and simple way.",
            bookNow: "Book now",
            explore: "Explore specialties",
            happyPatients: "Happy patients",
            licensedDoctors: "Licensed doctors",
            alwaysAvailable: "Always available"
},
    specialtiesPanel: {
            title: "Specialties",
            subtitle: "Choose the right specialty and find experienced doctors for your case.",
            viewAll: "View all",
            doctors: "doctors",
            neurology: "Neurology",
            orthopedics: "Orthopedics",
            oncology: "Oncology",
            ent: "ENT",
            ophthalmology: "Ophthalmology",
            cardiology: "Cardiology",
            pulmonology: "Pulmonology",
            nephrology: "Nephrology",
            dentistry: "Dentistry",
            pediatrics: "Pediatrics",
            dermatology: "Dermatology",
            gynecology: "Gynecology"
},
    structure: {
            title: "How it works",
            subtitle: "Three simple steps to find the right doctor and schedule your visit.",
            step: "STEP",
            step1Title: "Search by specialty",
            step1Desc:"Browse specialties and filter doctors based on your exact medical need.",
            step2Title: "Choose your doctor",
            step2Desc:"Compare ratings, fees, and clinic locations before selecting the doctor.",
            step3Title: "Book instantly",
            step3Desc:"Reserve your appointment in seconds and receive confirmation right away."
},
    aboutPage: {
            badge: "Medaura",
            title: "About Us",
            description1:"At Medaura, we believe that access to healthcare should be simple and fast. We connect patients with the best doctors and clinics, helping them choose the right specialty and book appointments with confidence, without complexity or waiting.",
            description2:"Our goal is to make the search and booking experience more clear, from comparing reviews and consultation fees to confirming appointments, while maintaining service quality and patient comfort at every step.",
            feature1: "Trusted Care",
            feature2: "Faster Booking",
            feature3: "Certified Doctors"
},
    appointmentsPage: {
            badge: "Appointments",
            title: "Upcoming appointments & visit history",
            filter: "Filter by date",
            apply: "Apply",
            total: "Total Appointments",
            today: "Today's Appointments",
            current: "Currently Showing",
            empty: "No appointments found for the selected date."
},
    testimonials: {
            title: "What clients say",
            subtitle: "Real feedback from patients who booked through Medaura.",
            text1: "Booking was smooth, and I found the right doctor quickly. The clinic experience was excellent.",
            text2: "I compared doctors by rating and fee in minutes. The appointment confirmation was instant.",
            text3: "Great platform for family appointments. Clear info, responsive support, and trusted clinics."
},
    clinicBest: {
            title: "Best Clinics",
            subtitle: "Trusted clinics with high patient satisfaction and modern facilities.",
            viewAll: "View clinics",
            viewProfile: "View Profile",
            location: "Location"
},
    doctorsDetails: {
            title: "Most Booked Doctors",
            subtitle: "Top doctors with strong ratings and verified clinical experience.",
            viewAll: "View All Doctors",
            viewProfile: "View Profile",
            sessionFee: "Session Fee",
            experience: "Experience",
            years: "years",
            consultantOrthopedics: "Consultant Orthopedics",
            consultantDentistry: "Consultant Dentistry",
            consultantCardiology: "Consultant Cardiology",
            badge: "✨ Best Certified Doctors in Egypt",
            searchPlaceholder: "Search by doctor name or specialty...",
            allSpecialties: "All Specialties",
            neurology: "Neurology",
            orthopedics: "Orthopedics",
            oncology: "Oncology",
            ent: "ENT",
            ophthalmology: "Ophthalmology",
            cardiology: "Cardiology",
            pulmonology: "Pulmonology",
            nephrology: "Nephrology",
            dentistry: "Dentistry",
            pediatrics: "Pediatrics",
            dermatology: "Dermatology",
            obgyn: "OB-GYN",
            allPrices: "All Prices",
            under200: "Under 200",
            "200to500": "200 - 500",
            "500to1000": "500 - 1000",
            over1000: "Over 1000",
            consultationPrice: "Consultation Price",
            gender: "Gender",
            all: "All",
            male: "Male",
            female: "Female",
            sortBy: "Sort By",
            topRated: "Top Rated",
            priceLowHigh: "Price: Low to High",
            priceHighLow: "Price: High to Low",
            alphabetical: "Alphabetical",
            showing: "Showing",
            of: "of",
            doctors: "doctors",
            page: "Page"
},
    login: {
            logo: "Medaura",
            login: "Login",
            signUp: "Sign Up",
            email: "Email Address",
            emailPlaceholder: "example@email.com",
            password: "Password",
            passwordPlaceholder: "Enter your password",
            rememberMe: "Remember me",
            forgotPassword: "Forgot Password?",
            noAccount: "Don't have an account?",
            invalidEmail: "Please enter a valid email",
            emailRequired: "Email is required",
            passwordRequired: "Password is required",
            passwordMin: "Password must be at least 6 characters",
            loading: "Logging in...",
            success: "Login successful.",
            loginFailed: "Incorrect email or password."
},
    register: {
            nameRequired: "Full name is required",
            invalidEmail: "Invalid email address",
            emailRequired: "Email is required",
            passwordStrong: "Password must contain at least one letter and one number (min 8 characters)",
            passwordRequired: "Password is required",
            passwordMatch: "Passwords do not match",
            confirmPasswordRequired: "Confirm password is required",
            agreeRequired: "You must agree to the terms",
            specializationRequired: "Specialization is required for doctors",
            registerFailed: "Registration failed, please try again",
            patient: "Patient",
            doctor: "Doctor",
            fullName: "Full Name",
            specialization: "Specialization",
            chooseSpecialization: "Choose Specialization",
            cardiology: "Cardiology",
            dermatology: "Dermatology",
            neurology: "Neurology",
            pediatrics: "Pediatrics",
            psychiatry: "Psychiatry",
            radiology: "Radiology",
            surgery: "Surgery",
            email: "Email",
            emailPlaceholder: "Enter your email",
            password: "Password",
            passwordPlaceholder: "Enter your password",
            confirmPassword: "Confirm Password",
            confirmPasswordPlaceholder: "Re-enter your password",
            agree: "I agree to the terms and conditions",
            login: "Login",
            signUp: "Sign Up",
            loading: "Signing up..."
},
    forgetPassword: {
            login: "Login",
            signUp: "Sign Up",
            title: "Forgot Password",
            subtitle: "Don't worry, we'll send you instructions to reset it.",
            email: "Email Address",
            emailPlaceholder: "example@email.com",
            send: "Send",
            backToLogin: "Back to Login",
            invalidEmail: "Please enter a valid email address",
            emailRequired: "Email is required",
            loading: "Sending...",
            success: "Password reset link has been sent to your email.",
            failed: "Something went wrong. Please try again."
},
    resetPassword: {
            title: "Reset Password",
            subtitle: "Enter your new password",
            newPassword: "New Password",
            newPasswordPlaceholder: "Enter your new password",
            confirmPassword: "Confirm Password",
            confirmPasswordPlaceholder: "Confirm your new password",
            reset: "Reset Password",
            loading: "Saving...",
            success: "Password changed successfully",
            failed: "Failed to reset password"
},
    verifyOtp: {
            title: "Verify OTP",
            subtitle: "Enter the verification code sent to your email.",
            email: "Email",
            verify: "Verify",
            loading: "Verifying...",
            success: "OTP verified successfully.",
            failed: "Invalid verification code.",
            invalidCode: "Please enter the 6-digit code.",
            didntReceive: "Didn't receive the code?",
            resend: "Resend Code",
            resent: "Code sent again successfully."
},

    contactDetails: {
            title: "Page Not Found",
            description: "Sorry, the page you're looking for doesn't exist or has been moved.",
            backHome: "Back to Home"
},
    clinicsPage: {
            title: "Clinics",
            subtitle: "Best clinics based on user reviews and experiences",
            search: "Search clinics by name or city...",
            doctors: "Doctors",
            details: "View Details",
            noResults: "No clinics found"
},
    navbar: {
            search: "Search...",
            lightMode: "Light mode",
            darkMode: "Dark mode",
            notifications: "Notifications",
            notification: "Notification",
            markAllRead: "Mark all read",
            noNotifications: "No notifications",
            clearAll: "Clear all",
            viewAll: "View all",
            logout: "Sign out",
            openSidebar: "Open sidebar",
            now: "Now",
            defaultDoctor: "Dr. Mohamed Ismail",
            defaultSpecialist: "Cardiologist"
} ,
    chartBar: {
            title: "Patient Statistics",
            showAll: "Show All",
            newPatients: "New Patients",
            existingPatients: "Existing Patients",
            totalPatients: "Total Patients",
            noData: "No Data Available",
            noDataSubtitle: "No data available for this period"
},
    dashboardHeader: {
            title: "Overview",
            subtitle: "Track performance and daily visits",
            chooseDate: "Choose Date",
            cancel: "Cancel",
            apply: "Apply"
},
    patients: {
            title: "Patients",
            count: "patients",
            search: "Search patient...",
            name: "Name",
            gender: "Gender",
            department: "Department",
            lastVisit: "Last Visit",
            noPatients: "No patients found"
}, 
    ProfileDetail: {
            welcome: "Welcome to Patient Profile",
            summaryDesc: "Here you will find a summary of your account, visit history, prescriptions, and everything you need to easily track your health status.",
            visits: "Visits",
            prescriptions: "Prescriptions",
            lastUpdate: "Last Update",
            defaultUser: "User",
            email: "Email",
            patient: "patient",
            phone: "Phone Number",
            dob: "Date of Birth",
            gender: "Gender",
            quickMenu: "Quick Menu",
            navProfile: "Profile",
            navHistory: "Visit History",
            navPrescriptions: "Prescriptions",
            navFollowup: "Follow-up",
            updateProfile: "Update Profile",
            profileSubtitle: "Your Personal Details",
            profilePhoto: "Profile Photo",
            noPhoto: "No image",
            chooseNewPhoto: "Choose a new photo",
            photoRequirements: "JPG, PNG max 5MB",
            changePhoto: "Change photo",
            savePhoto: "Save photo",
            savingPhoto: "Uploading...",
            photoSuccess: "Photo updated successfully.",
            fullNameLabel: "Full Name",
            phonePlaceholder: "010XXXXXXXX",
            genderUnspecified: "Unspecified",
            genderMale: "Male",
            genderFemale: "Female",
            changesSuccess: "Changes saved successfully.",
            saveChanges: "Save Changes",
            savingChanges: "Saving...",
            reset: "Reset",
            changePasswordTitle: "Change Password",
            changePasswordSubtitle: "Update your account password",
            currentPasswordLabel: "Current Password",
            newPasswordLabel: "New Password",
            confirmPasswordLabel: "Confirm New Password",
            updatePasswordBtn: "Update Password",
            updatingPassword: "Updating...",
            historyTitle: "Your Visits History",
            historySubtitle: "Last Visits",
            historyCount: "Showing {count} visit(s)",
            loadingHistory: "Loading history...",
            noHistory: "No visits recorded yet.",
            doctor: "Doctor",
            time: "Time",
            pendingAccess: "The doctor is requesting access to write a prescription for this booking",
            accept: "Accept",
            reject: "Reject",
            acceptedAccess: "Doctor has been granted access to write a prescription",
            revokeAccess: "Revoke Access",
            rejectedAccess: "Prescription access has been rejected/revoked",
            allowAccess: "Allow Access",
            prescriptionsTitle: "Prescriptions",
            prescriptionsSubtitle: "Recent Prescriptions",
            prescriptionsCount: "Showing {count} prescription(s)",
            loadingPrescriptions: "Loading prescriptions...",
            noPrescriptions: "No prescriptions found yet.",
            noDate: "No Date",
            prescriptionNumber: "Prescription #{id}",
            diagnosis: "Diagnosis",
            medication: "Medication",
            tests: "Tests/Labs",
            notes: "Notes",
            generalError: "An error occurred",
            defaultUser: "User",
            prescriptionDetails: "Prescription Details",
            dose: "Dose",
            duration: "Duration",
            forDuration: "for {duration}",
            followupTitle: "Status Follow-up",
            followupSubtitle: "Follow-up Plan",
            followupDesc: "Quick update on your health status",
            recommendationsTitle: "Recommendations",
            recommendationsText: "Follow up with your doctor regularly, keep track of symptoms, and bring lab results to every visit.",
            tipsTitle: "Important Tips",
            tipsText: "You can update your phone number and notes at any time and click save to ensure messages reach you easily.",
            notAvailable: "N/A",
            checkingAccount: "Checking your account...",
            needLoginTitle: "You need to log in",
            needLoginDesc: "Please log in first to view your personal profile and visit history.",
            status: "Status",
            successAlert: "Success!",
            successMsg: "Password changed successfully",
            alertError: "Error",
            alertFillFields: "Please fill in all password fields",
            alertMinLength: "Password must be at least 8 characters long",
            alertMatchError: "New password and confirmation do not match",
            changePasswordFail: "Failed to change password",
            symptoms: "Symptoms",
            logout: "Logout",
            
        },
    bookingStatus: {
            pending: "Pending",
            confirmed: "Confirmed",
            completed: "Completed",
            cancelled: "Cancelled"
            },
    visitsGauge: {
            showAll: "Show All",
            title: "Patient Visits",
            allPatients: "All Patients",
            male: "Male",
            female: "Female",
            sinceLastWeek: "Since last week"
},
    sidebar: {
            home: "Home",
            healthcare: "Healthcare",
            management: "Management",
            dashboard: "Dashboard",
            patients: "Patients",
            appointments: "Appointments",
            prescriptions: "Prescriptions",
            financial: "Financial",
            notifications: "Notifications",
            settings: "Settings",
            doctorDashboard: "Doctor Dashboard",
            closeSidebar: "Close sidebar"
},
    
    adminDash: {
            totalDoctors: "Total Doctors",
            totalPatients: "Total Patients",
            totalClinics: "Total Clinics",
            totalStaff: "Total Staff",
    },
    notificationsPage: {
      title: "Notifications",
      subtitle: "Stay updated with your latest alerts.",
      backHome: "Back Home",
      markAllRead: "Mark all as read",
      loading: "Loading notifications...",
      noNotifications: "No notifications yet",
      noNotificationsDesc: "You're all caught up! We'll notify you when something important happens.",
      newNotification: "New Notification",
      markAsRead: "Mark as read",
      recently: "Recently",
      error: "Error: "
    },
    contactPage: {
      getInTouch: "Get In Touch",
      title: "Contact Us",
      subtitle: "Have questions or need assistance? We are here to help! Send us a message and our team will get back to you shortly.",
      callUs: "Call Us",
      callUsDesc: "Sat-Thu from 9am to 6pm.",
      emailUs: "Email Us",
      emailUsDesc: "We usually reply within 24 hours.",
      visitUs: "Visit Us",
      visitUsDesc1: "123 Health Avenue, Medical District",
      visitUsDesc2: "Cairo, Egypt",
      sendMessage: "Send a Message",
      messageSent: "Message Sent Successfully!",
      messageSentDesc: "Thank you for reaching out. We have received your message and will contact you soon.",
      sendAnother: "Send Another Message",
      fullName: "Full Name",
      email: "Email Address",
      subject: "Subject",
      message: "Message",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@example.com",
      subjectPlaceholder: "How can we help?",
      messagePlaceholder: "Write your message here...",
      sendBtn: "Send Message"
    },
    dashboard: {
            sidebar: {
                    home: "Home",
                    healthcare: "Healthcare",
                    management: "Management",
                    dashboard: "Dashboard",
                    patients: "Patients",
                    doctors: "Doctors",
                    appointments: "Appointments",
                    clinicDoctors: "Clinic Doctors",
                    clinics: "Clinics",
                    staff: "Staff",
                    auditLogs: "Audit Logs",
                    notifications: "Notifications",
                    settings: "Settings"
            }
    }
};

export default en;